version: '2'
services:
	estest1:
	  image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
	  volumes:
	    - /data/elasticsearch/data
	    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
	  ports:
	    - 9200:9200
	    - 9300:9300