version: '2'
services:
  elasticsearch1:
    image: elasticsearch:latest
    container_name: elasticsearch1
    restart: on-failure
    network_mode: bridge
    working_dir: /data/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xms1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/es.alice.products.comments.prd/data:/data/elasticsearch/data
      - /data/es.alice.products.comments.prd/logs:/data/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    network_mode: "bridge"

  kibana-prd:  
    image: kibana:latest  
    container_name: kibana-prd  
    restart: always
    ports:  
       - "5601:5601"  
    links:  
       - elasticsearch1:elasticsearch
    network_mode: "bridge"

  logstash:
      image: logstash:latest
      container_name: logstash 
      restart: always
      network_mode: "bridge"
      ports:
        - "5044:5044"
        - "4560:4560"
        - "8080:8080"
      volumes:
        - ./conf:/config-dir
        - ./patterns:/opt/logstash/patterns
      links:
        - elasticsearch1:elasticsearch
      command: logstash -f /config-dir
